# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

github: schneegans
ko_fi: schneegans
custom:
  [
    'https://www.paypal.com/donate/?hosted_button_id=3F7UFL8KLVPXE',
    https://schneegans.cb.id,
  ]
