//////////////////////////////////////////////////////////////////////////////////////////
//   _  _ ____ _  _ ___  ____                                                           //
//   |_/  |__| |\ | |  \ |  |    This file belongs to Kando, the cross-platform         //
//   | \_ |  | | \| |__/ |__|    pie menu. Read more on github.com/kando-menu/kando     //
//                                                                                      //
//////////////////////////////////////////////////////////////////////////////////////////

// SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
// SPDX-License-Identifier: MIT

/**
 * This is a mapping from the DOM key names to the Win32 virtual key names. This is based
 * on this list:
 * https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values
 *
 * The Alt key is not included in this list, because it is handled separately.
 *
 * @todo: Is VK_APPS correct for the context menu key? Shouldn't it be VK_MENU?
 */
export const WindowsKeyNames = new Map<string, string>([
  ['Attn', 'VK_ATTN'], // (0xF6)
  ['CapsLock', 'VK_CAPITAL'], // (0x14)
  ['Cancel', 'VK_CANCEL'], // (0x03)
  ['Control', 'VK_CONTROL'], // (0x11)
  ['Meta', 'VK_LWIN'], // (0x5B)
  ['NumLock', 'VK_NUMLOCK'], // (0x90)
  ['ScrollLock', 'VK_SCROLL'], // (0x91)
  ['Shift', 'VK_SHIFT'], // (0x10)
  ['Enter', 'VK_RETURN'], // (0x0D)
  ['Tab', 'VK_TAB'], // (0x09)
  [' ', 'VK_SPACE'], // (0x20)
  ['ArrowDown', 'VK_DOWN'], // (0x28)
  ['ArrowLeft', 'VK_LEFT'], // (0x25)
  ['ArrowRight', 'VK_RIGHT'], // (0x27)
  ['ArrowUp', 'VK_UP'], // (0x26)
  ['End', 'VK_END'], // (0x23)
  ['Home', 'VK_HOME'], // (0x24)
  ['PageDown', 'VK_NEXT'], // (0x22)
  ['PageUp', 'VK_PRIOR'], // (0x21)
  ['Backspace', 'VK_BACK'], // (0x08)
  ['Clear', 'VK_CLEAR'], // (0x0C)
  ['CrSel', 'VK_CRSEL'], // (0xF7)
  ['Delete', 'VK_DELETE'], // (0x2E)
  ['EraseEof', 'VK_EREOF'], // (0xF9)
  ['ExSel', 'VK_EXSEL'], // (0xF8)
  ['Insert', 'VK_INSERT'], // (0x2D)
  ['Accept', 'VK_ACCEPT'], // (0x1E)
  ['Attn', 'VK_OEM_ATTN'], // (0xF0)
  ['ContextMenu', 'VK_APPS'], // (0x5D)
  ['Escape', 'VK_ESCAPE'], // (0x1B)
  ['Execute', 'VK_EXECUTE'], // (0x2B)
  ['Finish', 'VK_OEM_FINISH'], // (0xF1)
  ['Help', 'VK_HELP'], // (0x2F)
  ['Pause', 'VK_PAUSE'], // (0x13)
  ['Play', 'VK_PLAY'], // (0xFA)
  ['Select', 'VK_SELECT'], // (0x29)
  ['PrintScreen', 'VK_SNAPSHOT'], // (0x2C)
  ['Standby', 'VK_SLEEP'], // (0x5F)
  ['Alphanumeric', 'VK_OEM_ATTN'], // (0xF0)
  ['Convert', 'VK_CONVERT'], // (0x1C)
  ['FinalMode', 'VK_FINAL'], // (0x18)
  ['ModeChange', 'VK_MODECHANGE'], // (0x1F)
  ['NonConvert', 'VK_NONCONVERT'], // (0x1D)
  ['Process', 'VK_PROCESSKEY'], // (0xE5)
  ['HangulMode', 'VK_HANGUL'], // (0x15)
  ['HanjaMode', 'VK_HANJA'], // (0x19)
  ['JunjaMode', 'VK_JUNJA'], // (0x17)
  ['Hankaku', 'VK_OEM_AUTO'], // (0xF3)
  ['Hiragana', 'VK_OEM_COPY'], // (0xF2)
  ['KanaMode', 'VK_KANA'], // (0x15)
  ['KanjiMode', 'VK_KANJI'], // (0x19)
  ['Katakana', 'VK_OEM_FINISH'], // (0xF1)
  ['Romaji', 'VK_OEM_BACKTAB'], // (0xF5)
  ['Zenkaku', 'VK_OEM_ENLW'], // (0xF4)
  ['F1', 'VK_F1'], // (0x70)
  ['F2', 'VK_F2'], // (0x71)
  ['F3', 'VK_F3'], // (0x72)
  ['F4', 'VK_F4'], // (0x73)
  ['F5', 'VK_F5'], // (0x74)
  ['F6', 'VK_F6'], // (0x75)
  ['F7', 'VK_F7'], // (0x76)
  ['F8', 'VK_F8'], // (0x77)
  ['F9', 'VK_F9'], // (0x78)
  ['F10', 'VK_F10'], // (0x79)
  ['F11', 'VK_F11'], // (0x7A)
  ['F12', 'VK_F12'], // (0x7B)
  ['F13', 'VK_F13'], // (0x7C)
  ['F14', 'VK_F14'], // (0x7D)
  ['F15', 'VK_F15'], // (0x7E)
  ['F16', 'VK_F16'], // (0x7F)
  ['F17', 'VK_F17'], // (0x80)
  ['F18', 'VK_F18'], // (0x81)
  ['F19', 'VK_F19'], // (0x82)
  ['F20', 'VK_F20'], // (0x83)
  ['MediaPlayPause', 'VK_MEDIA_PLAY_PAUSE'], // (0xB3)
  ['MediaStop', 'VK_MEDIA_STOP'], // (0xB2)
  ['MediaTrackNext', 'VK_MEDIA_NEXT_TRACK'], // (0xB0)
  ['MediaTrackPrevious', 'VK_MEDIA_PREV_TRACK'], // (0xB1)
  ['AudioVolumeDown', 'VK_VOLUME_DOWN'], // (0xAE)
  ['AudioVolumeMute', 'VK_VOLUME_MUTE'], // (0xAD)
  ['AudioVolumeUp', 'VK_VOLUME_UP'], // (0xAF)
  ['ZoomToggle', 'VK_ZOOM'], // (0xFB)
  ['LaunchMail', 'VK_LAUNCH_MAIL'], // (0xB4)
  ['LaunchMediaPlayer', 'VK_LAUNCH_MEDIA_SELECT'], // (0xB5)
  ['LaunchApplication1', 'VK_LAUNCH_APP1'], // (0xB6)
  ['LaunchApplication2', 'VK_LAUNCH_APP2'], // (0xB7)
  ['BrowserBack', 'VK_BROWSER_BACK'], // (0xA6)
  ['BrowserFavorites', 'VK_BROWSER_FAVORITES'], // (0xAB)
  ['BrowserForward', 'VK_BROWSER_FORWARD'], // (0xA7)
  ['BrowserHome', 'VK_BROWSER_HOME'], // (0xAC)
  ['BrowserRefresh', 'VK_BROWSER_REFRESH'], // (0xA8)
  ['BrowserSearch', 'VK_BROWSER_SEARCH'], // (0xAA)
  ['BrowserStop', 'VK_BROWSER_STOP'], // (0xA9)
  ['Decimal', 'VK_DECIMAL'], // (0x6E)
  ['Multiply', 'VK_MULTIPLY'], // (0x6A)
  ['Add', 'VK_ADD'], // (0x6B)
  ['Divide', 'VK_DIVIDE'], // (0x6F)
  ['Subtract', 'VK_SUBTRACT'], // (0x6D)
  ['Separator', 'VK_SEPARATOR'], // (0x6C)
]);
