# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

name: Deploy to Winget

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download release asset
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          regex: true
          file: 'Kando-.*x64\.exe'
      - uses: actions/checkout@v4
      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1.6.0
        id: get-latest-tag
      - name: Publish to Winget
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: KandoMenu.Kando
          installers-regex: 'Kando-.*x64\.exe$'
          release-tag: ${{ steps.get-latest-tag.outputs.tag }}
          token: ${{ secrets.WINGET_TOKEN }}
